//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailOrder
    {
        public int IdDeOrder { get; set; }
        public Nullable<int> IdDeCart { get; set; }
        public string Address { get; set; }
    
        public virtual DetailCart DetailCart { get; set; }
    }
}
