//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailImportGood
    {
        public int IdDeIm { get; set; }
        public string IdIm { get; set; }
        public string IdGoods { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<float> SumMoney { get; set; }
    
        public virtual ImportGood ImportGood { get; set; }
    }
}
