//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListRequest
    {
        public int IdRe { get; set; }
        public Nullable<System.DateTime> DateRe { get; set; }
        public string NameCustomer { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string TypeProject { get; set; }
        public string Service { get; set; }
        public string ContentRequest { get; set; }
    }
}
