//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubImgDesign
    {
        public int IdSub { get; set; }
        public Nullable<int> IdDe { get; set; }
        public string ImageSubDe { get; set; }
    
        public virtual DesignFurniture DesignFurniture { get; set; }
    }
}
