//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubImage
    {
        public int IdSubImage { get; set; }
        public string IdGoods { get; set; }
        public string SubImage1 { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
